changelog:
  categories:
    - title: Security
      labels:
        - security
    - title: Removed
      labels:
        - removed
    - title: Deprecated
      labels:
        - deprecated
    - title: Added
      labels:
        - added
    - title: Changed
      labels:
        - changed
    - title: Fixed
      labels:
        - fixed
    - title: Documentation
      labels:
        - docs
    - title: Internals
      labels:
        - chore
        - refactor
        - dependencies
    - title: Other Changes
      labels:
        - "*"
