name: Publish on Tag

# This action:
#   - Is triggered when a new version is tagged;
#   - Check if the package version match the repository tag;
#   - Build and publish the packages to test-PyPI and/or PyPI.

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
  
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.14

      - name: Get project's version
        id: poetry-package-version
        run: |
          echo "Poetry version is: $(poetry version --short)"
          echo "::set-output name=version::$(poetry version --short)"

      - name: Fail if package version doesn't match the tag
        if: ${{ github.ref_name != steps.poetry-package-version.outputs.version }}
        run: |
          echo "Poetry package version doesn't match tag!"
          echo "tag=${{ github.ref_name }}, version=${{ steps.poetry-package-version.outputs.version }}"
          exit 1

      # - name: Build and publish on test-PyPI
      #   run: |
      #     poetry config repositories.test-pypi https://test.pypi.org/legacy/
      #     poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
      #     poetry build
      #     poetry publish -r test-pypi

      - name: Build and publish on PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish
      
      - name: Create release changelog
        run: poetry run semversioner changelog --template .semversioner/templates/release.j2 > body.md

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*.tar.gz,./dist/*.whl"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}